FROM hthakkar/finex-base-osjdk:latest

ADD target/finex-config-server-0.0.1-SNAPSHOT.jar /
RUN touch /firststart.txt

RUN mkdir /finex-config-git

EXPOSE 8443/tcp

WORKDIR /
ENTRYPOINT cd / && \
if [ -f /firststart.txt ]; then \
keytool -import -noprompt -trustcacerts -alias internalca -cacerts -file /finex-security/internal-ca.crt -storepass changeit; \
rm /firststart.txt; \
else echo 'Cert already imported'; fi && \
java -jar ./finex-config-server-0.0.1-SNAPSHOT.jar
   
